### ISSUE TITLE
Off by one error for maxErrors

### ISSUE THREAD

**Issue by breml** [krakendio/krakend-circuitbreaker#3]
In my tests I played with very low values for `maxErrors` (e.g. 2) and I see always `maxErrors + 1` hits in my backend, before the cricuit breaker kicks in.

I assume, the reason is, the following line in `gobreaker.go` (https://github.com/devopsfaith/krakend-circuitbreaker/blob/master/gobreaker/gobreaker.go#L95)

```Go
return counts.ConsecutiveFailures > uint32(cfg.MaxErrors)
```

I assume, the condition should be:

```Go
return counts.ConsecutiveFailures >= uint32(cfg.MaxErrors)
```

**Comment by kpacha** [comment]
that's the expected behaviour, the first error after the limit opens the circuit.

https://github.com/devopsfaith/krakend-circuitbreaker/blob/master/gobreaker/proxy/proxy_test.go#L81-L122

**Comment by breml** [comment]
@kpacha If this is the expected behavior, then at least in my opinion, the name of the config setting (`maxErrors`) is misleading. If I see `max`, then I expect that there are not more errors than I configured until the circuit is opened. But this is not the case here, because as you have written, the first error *after* the max (or as you have written *limit*) opens the circuit.
If you tell someone to give you max 10 EUR, and this person starts to give you 1 EUR coins, the expected behavior is, that it stops at 10 EUR and not that the first EUR after the 10th EUR "opens the circuit", because then the other person has payed you already 11 EUR.

I am aware, that this is a little bit nitpicking, but I still feel, we have a of-by-one situation here.

**Comment by alombarte** [comment]
Hi @breml , this issue was forgotten in the deepness of GH issues. Apologies for that.

Either we merge https://github.com/krakendio/krakend-circuitbreaker/pull/11 or discard it all, but the issue is coming to a resolution.

**Comment by alombarte** [comment]
We will leave the semantics as is.
The `MaxErrors` is the maximum number of errors you are willing to tolerate with the closed circuit. If you reach the maximum the system decides on the next request to open or leave it closed
